/**
 * Unsubscribe Token (HMAC over email)
 *
 * Stable, deterministic token used to prove that the unsubscribe request
 * came from someone who received the original email. Generated at email
 * send-time, embedded in the unsubscribe link, verified at click-time.
 *
 * Stable means: the same email always produces the same token (given the
 * secret). This is intentional — a recipient might open the email weeks
 * later and the link must still work. There is no expiry.
 *
 * The HMAC prevents anyone who only knows the email from unsubscribing
 * the address (the SEC-8 finding from the audit).
 *
 * Implementation uses Web Crypto SubtleCrypto so it's edge-runtime safe,
 * matching the CSRF token pattern in src/lib/csrf.ts.
 */

import 'server-only'

import { env } from '@/env'

// Same gating story as src/lib/csrf.ts — env.ts already enforces
// CSRF_SECRET presence on production (VERCEL_ENV='production') deploys.
// Don't throw at module load here, otherwise PR preview builds (where
// NODE_ENV is always 'production' during `next build` but VERCEL_ENV is
// 'preview') would crash even though env.ts validated successfully.
const SECRET = env.CSRF_SECRET ?? 'dev-csrf-secret-for-local-development-only'

async function hmacHex(message: string): Promise<string> {
	const encoder = new TextEncoder()
	const key = await crypto.subtle.importKey(
		'raw',
		encoder.encode(SECRET),
		{ name: 'HMAC', hash: 'SHA-256' },
		false,
		['sign']
	)
	const sig = await crypto.subtle.sign('HMAC', key, encoder.encode(message))
	return Array.from(new Uint8Array(sig))
		.map(b => b.toString(16).padStart(2, '0'))
		.join('')
}

function normaliseEmail(email: string): string {
	return email.trim().toLowerCase()
}

/** Produce the unsubscribe token for a subscriber email. */
export function generateUnsubscribeToken(email: string): Promise<string> {
	return hmacHex(`unsub:${normaliseEmail(email)}`)
}

const SITE_URL = 'https://hudsondigitalsolutions.com'

/** Build the canonical unsubscribe URL for an email recipient. */
export async function buildUnsubscribeUrl(email: string): Promise<string> {
	const token = await generateUnsubscribeToken(email)
	const params = new URLSearchParams({ email, token })
	return `${SITE_URL}/unsubscribe?${params.toString()}`
}

/**
 * Constant-time comparison of an incoming token with the expected HMAC.
 * Returns true iff the token was generated by us for this email.
 */
export async function verifyUnsubscribeToken(
	email: string,
	token: string
): Promise<boolean> {
	if (!token) {
		return false
	}
	const expected = await hmacHex(`unsub:${normaliseEmail(email)}`)
	if (expected.length !== token.length) {
		return false
	}
	let result = 0
	for (let i = 0; i < expected.length; i++) {
		result |= expected.charCodeAt(i) ^ token.charCodeAt(i)
	}
	return result === 0
}
