blank_issues_enabled: false
contact_links:
  - name: 🚀 Quick Question or Discussion
    url: https://github.com/hudsondigitalsolutions/business-website/discussions
    about: For general questions, ideas, or discussions that don't require a formal issue
  - name: 📧 Direct Contact
    url: https://hudsondigitalsolutions.com/contact
    about: For business inquiries or sensitive matters that require direct communication